### ISSUE TITLE
Artigo DEV.to

### ISSUE THREAD

**Issue by lariadeoliveira** [anatechdev/mulheres-na-tecnologia#42]
Olá, gostaria de deixar o link do meu artigo no Dev.to 

[https://dev.to/larideoliiveira/transicao-de-carreira-3c9c](url)

Obrigado =)

**Comment by anamariasilva** [comment]
Obrigada pela contribuição, @lariadeoliveira

**Comment by anamariasilva** [comment]
Artigo incluído no repositório, obrigada @lariadeoliveira
