### ISSUE TITLE
Adicionando Jakeliny Gracielly

### ISSUE THREAD

**Issue by madalena-rocha** [anatechdev/mulheres-na-tecnologia#45]
Adicionando conteúdo produzido por Jakeliny Gracielly (Microsoft MVP e DevRel na Rocketseat)

**Comment by madalena-rocha** [comment]
Gostaria de contribuir com este repositório adicionando conteúdo produzido por Jakeliny Gracielly. Poderia, por favor, atribuir esta issue a mim? @anatechdev

**Comment by anamariasilva** [comment]
Obrigada pela contribuição, solicite a inclusão do conteúdo no repositório.
